[database]
uri = "mongodb://127.0.0.1:27017"
name = "qamaits"
collections = [
    {name ="users"},
    {name="posts"},
    {name="media"},
    {name="oauth"},
]

[server]
address = "127.0.0.1"
port = 443
access_log = "access_log.log"
tls_key = "tls/localhost+2-key.pem"
tls_cert = "tls/localhost+2.pem"

[oauth]
auths = [
    {name = "google", client_id = "310275617031-hshscsl18isn7dndjqe1kgb0apsj7b0r.apps.googleusercontent.com", client_secret = "VYj3hgFs42W_glikGqGXZb-S", scope = ["https://www.googleapis.com/auth/gmail.send"], api_key = "AIzaSyByd0SacdforVc4_K8ZEJlpRSgu4hy1NUI"},
]

[email]
from_address = "mott.ian77@gmail.com"
provider = "google"
