[database]
uri = "mongodb://127.0.0.1:27017"
name = "qamaits"
collections = [
    {name ="users"},
    {name="posts"},
    {name="media"},
    {name="oauth"},
]

[server]
address = "127.0.0.1"
port = 443
access_log = "access_log.log"
tls_key = "tls/localhost+2-key.pem"
tls_cert = "tls/localhost+2.pem"
hostname = "localhost"

[oauth]
auths = [
    {name = "google", client_id = "CLIENT_ID", client_secret = "CLIENT_SECRET", auth_url = "https://accounts.google.com/o/oauth2/v2/auth", token_url = "https://www.googleapis.com/oauth2/v3/token", scope = ["https://www.googleapis.com/auth/gmail.send"], api_key = "API_KEY"},
]

[email]
from_address = "EMAIL_ADDRESS"
provider = "google"
